### ISSUE TITLE
Cannot run job on cluster

### ISSUE THREAD

**Issue by camer314** [james-tn/ray-on-aml#4]
``Thanks for a very promising library.

I am trying to run a basic 'hello world' job on my cluster, this is what I have setup:

- Cluster with VNET
- A basic docker image that consists of

```
FROM ubuntu:20.04
RUN apt-get update && apt-get install -y python3-pip
RUN apt-get update && apt-get install -y python-is-python3
RUN pip install ray-on-aml ray azureml-core
```

- A copy of your sample script

```import ray
from azureml.core import Run
from ray import tune
from ray_on_aml.core import Ray_On_AML


if __name__ == "__main__":
    run = Run.get_context()
    ws = run.experiment.workspace
    ray_on_aml = Ray_On_AML()
    ray = ray_on_aml.getRay()

    if ray: #in the headnode
        print("head node detected")
    else:
        print("in worker node")
```

However this is giving me the error "Exception: For interactive use, please pass AML workspace to the init"

What should I expect to see happen? Is there any particular docker startup I need to do to initialize Ray before running your library? Seems like in the source code its throwing that exception because it fails to find a RANK environment variable but I do not know who sets that

**Comment by james-tn** [comment]
The AML job has to be of type distributed like below.

src = ScriptRunConfig(source_directory='../examples/job',
                script='aml_job.py',
                environment=rayEnv,
                compute_target=ray_cluster,
                distributed_job_config=PyTorchConfiguration(node_count=maxnode))
run = Experiment(ws, exp).submit(src)

See the example at the end of the https://github.com/james-tn/ray-on-aml/blob/master/examples/quick_use_cases.ipynb

**Comment by james-tn** [comment]
btw, you don't need to install ray. ray-on-aml has all ray core, ray tune, ray serve and ray rrlib as dependencies

**Comment by james-tn** [comment]
@camer314  did the problem get solved?

**Comment by camer314** [comment]
Sorry @james-tn I have moved on from this at the moment, I will close for now and circle back when I look at it once more
