### ISSUE TITLE
Adding Dependencies

### ISSUE THREAD

**Issue by RevanMacQueen** [james-tn/ray-on-aml#5]
Hello!

I'm trying to run a job on the cluster which has some dependencies in local python files. Workers on different nodes from the head return import error when running, stating these dependencies are not found. Is there a way to get the relevant dependencies on the worker nodes? Thanks!

**Comment by james-tn** [comment]
Are they not pip or conda packages?
If they are, you can add them to the cluster like below. The packages will be installed to all nodes:
ray_on_aml =Ray_On_AML(ws=ws, compute_cluster ="Name_of_Compute_Cluster", additional_pip_packages= \
['torch==1.10.0', 'torchvision', 'sklearn'])
Use additional_conda_packages  for conda

**Comment by RevanMacQueen** [comment]
They're local python modules, i.e. not pip or Conda packages.

**Comment by james-tn** [comment]
For now, please use AML job to handle that. I'll add support for interactive mode later. See the quick start example notebook at the end. Add your python dependencies file(s) to the same source folder as the main script. Remember to have distributed_job_config=PyTorchConfiguration(node_count=maxnode) in the ScriptRunConfig

**Comment by james-tn** [comment]
Another simple way to work around this is copy the content (class, functions) from the dependencies to a command in the main notebook and run it there so that you don't have to import. Ray will try to serialize them and send to the workers.

**Comment by james-tn** [comment]
@RevanMacQueen , please check this [example ](https://github.com/james-tn/ray-on-aml/blob/master/examples/others/advanced_configuration.ipynb) to see how a custom python module can be loaded in Interactive mode. The key is to use ray client.
